"""add start level to story

Revision ID: 02a5a51daa77
Revises: 8d3b1d852e28
Create Date: 2018-08-21 00:39:18.994736+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a5a51daa77'
down_revision = '8d3b1d852e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('introduction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('start_level_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_stories_start_level_id_levels'), 'levels', ['start_level_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stories_start_level_id_levels'), type_='foreignkey')
        batch_op.drop_column('start_level_id')
        batch_op.drop_column('introduction')

    # ### end Alembic commands ###
