"""Add race to character

Revision ID: 045db1289def
Revises: 02a5a51daa77
Create Date: 2018-08-22 18:30:04.684837+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045db1289def'
down_revision = '02a5a51daa77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_characters_race_id_races'), 'races', ['race_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_characters_race_id_races'), type_='foreignkey')
        batch_op.drop_column('race_id')

    # ### end Alembic commands ###
