"""add story

Revision ID: 056c80f7a9e7
Revises: 1af80ad51a6f
Create Date: 2018-08-20 21:55:30.680636+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056c80f7a9e7'
down_revision = '1af80ad51a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_levels_story_id_stories'), 'stories', ['story_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_levels_story_id_stories'), type_='foreignkey')
        batch_op.drop_column('story_id')

    op.drop_table('stories')
    # ### end Alembic commands ###
