"""add users characters relationship

Revision ID: 15987fb50aba
Revises: e67a297687ff
Create Date: 2018-07-21 01:33:37.075021+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15987fb50aba'
down_revision = 'e67a297687ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('intelligence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('speed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('strength', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_characters_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_characters_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('strength')
        batch_op.drop_column('speed')
        batch_op.drop_column('intelligence')
        batch_op.drop_column('health_points')

    # ### end Alembic commands ###
