"""ref character hit points

Revision ID: 1af80ad51a6f
Revises: 9f1ee870ce77
Create Date: 2018-08-20 21:09:34.670555+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af80ad51a6f'
down_revision = '9f1ee870ce77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hit_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_hit_points', sa.Integer(), nullable=True))
        batch_op.drop_column('health_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_points', sa.INTEGER(), nullable=True))
        batch_op.drop_column('max_hit_points')
        batch_op.drop_column('hit_points')

    # ### end Alembic commands ###
