"""add game level characters

Revision ID: 3c01d9b0e9a8
Revises: b14fc100ca05
Create Date: 2018-08-18 01:36:25.612512+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c01d9b0e9a8'
down_revision = 'b14fc100ca05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_level_characters',
    sa.Column('game_level_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('position_z', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_game_level_characters_character_id_characters')),
    sa.ForeignKeyConstraint(['game_level_id'], ['game_levels.id'], name=op.f('fk_game_level_characters_game_level_id_game_levels')),
    sa.PrimaryKeyConstraint('game_level_id', 'character_id', name=op.f('pk_game_level_characters'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_level_characters')
    # ### end Alembic commands ###
