"""add map_filename to level

Revision ID: 54d4af590ca9
Revises: d8d670b6e0ba
Create Date: 2018-08-31 01:48:57.282082+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d4af590ca9'
down_revision = 'd8d670b6e0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_filename', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_column('map_filename')

    # ### end Alembic commands ###
