"""add story to game

Revision ID: 8d3b1d852e28
Revises: 056c80f7a9e7
Create Date: 2018-08-21 00:29:54.059505+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3b1d852e28'
down_revision = '056c80f7a9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_games_story_id_stories'), 'stories', ['story_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_story_id_stories'), type_='foreignkey')
        batch_op.drop_column('story_id')

    # ### end Alembic commands ###
