"""remove game_level_character

Revision ID: 9d9b16e7c826
Revises: 045db1289def
Create Date: 2018-08-22 22:37:05.730164+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9b16e7c826'
down_revision = '045db1289def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_level_characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_level_characters',
    sa.Column('game_level_id', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('position_x', sa.INTEGER(), nullable=True),
    sa.Column('position_y', sa.INTEGER(), nullable=True),
    sa.Column('position_z', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='fk_game_level_characters_character_id_characters'),
    sa.ForeignKeyConstraint(['game_level_id'], ['game_levels.id'], name='fk_game_level_characters_game_level_id_game_levels'),
    sa.PrimaryKeyConstraint('game_level_id', 'character_id', name='pk_game_level_characters')
    )
    # ### end Alembic commands ###
