"""add gender to character

Revision ID: a33b567d5a44
Revises: 2248cc4389a9
Create Date: 2018-07-21 00:42:41.244062+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33b567d5a44'
down_revision = '2248cc4389a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('gender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_characters_gender_id_genders'), 'genders', ['gender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_characters_gender_id_genders'), type_='foreignkey')
        batch_op.drop_column('level')
        batch_op.drop_column('gender_id')
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
