"""add game levels

Revision ID: b14fc100ca05
Revises: bdd95e7c03ce
Create Date: 2018-08-17 22:51:11.216623+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14fc100ca05'
down_revision = 'bdd95e7c03ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(name='active_bool'), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_levels_game_id_games')),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_game_levels_level_id_levels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_levels'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_levels')
    # ### end Alembic commands ###
