"""rename statuses to conditions

Revision ID: b2e8de68f324
Revises: 3c01d9b0e9a8
Create Date: 2018-08-18 01:56:34.974473+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e8de68f324'
down_revision = '3c01d9b0e9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conditions'))
    )
    op.drop_table('statuses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_statuses')
    )
    op.drop_table('conditions')
    # ### end Alembic commands ###
