"""add character classes and relationship

Revision ID: dc011a059a5c
Revises: 15987fb50aba
Create Date: 2018-07-21 02:01:44.090456+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc011a059a5c'
down_revision = '15987fb50aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_classes'))
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_class_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_characters_character_class_id_character_classes'), 'character_classes', ['character_class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_characters_character_class_id_character_classes'), type_='foreignkey')
        batch_op.drop_column('character_class_id')

    op.drop_table('character_classes')
    # ### end Alembic commands ###
