"""add more character skills

Revision ID: dcfd2ebb1f8d
Revises: 24b77ab8fffe
Create Date: 2018-07-30 20:56:17.115635+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfd2ebb1f8d'
down_revision = '24b77ab8fffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charisma', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('constitution', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dexterity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wisdom', sa.Integer(), nullable=True))
        batch_op.drop_column('intelligence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intelligence', sa.INTEGER(), nullable=True))
        batch_op.drop_column('wisdom')
        batch_op.drop_column('dexterity')
        batch_op.drop_column('constitution')
        batch_op.drop_column('charisma')

    # ### end Alembic commands ###
