"""add user level and experience

Revision ID: e5dc415f5783
Revises: dc011a059a5c
Create Date: 2018-07-27 02:32:28.938939+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5dc415f5783'
down_revision = 'dc011a059a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_character_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_experience', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_experience')
        batch_op.drop_column('max_character_level')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
