"""add pronouns table

Revision ID: e761bdcbe7d0
Revises: a33b567d5a44
Create Date: 2018-07-21 00:56:42.176332+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e761bdcbe7d0'
down_revision = 'a33b567d5a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronouns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pronoun', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pronouns'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pronouns')
    # ### end Alembic commands ###
